name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_scouting:
    name: Test Scouting & Docker Compose build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: scoutingdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: tmpPass
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Vérification de la version installée

      - name: Clone Exercice-DDD repository
        run: |
          git clone https://github.com/AyaELMAFHOUM/Exercice-DDD.git
          ls -al Exercice-DDD
          ls -R Exercice-DDD

      - name: Build and start services with Docker Compose
        run: |
          cd Exercice-DDD/scouting-service
          docker-compose -f docker-compose.yml up --build -d

      - name: Wait for services to be ready
        run: |
          sleep 30  # Attendre un peu pour que les services se lancent

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd Exercice-DDD/scouting-service
          docker exec -t $(docker ps -q -f ancestor=scouting-service) mvn sonar:sonar \
            -Dsonar.projectKey=scouting-service \
            -Dsonar.host.url=https://c1b0-197-230-25-154.ngrok-free.app  \
            -Dsonar.login=$SONAR_TOKEN

      - name: Shutdown Docker Compose services
        run: |
          cd Exercice-DDD/scouting-service
          docker-compose -f docker-compose.yml down
