name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_scouting:
    name: Test Scouting & SonarQube analysis
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: scoutingdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: tmpPass
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven
      - name: Clone Exercice-DDD repository
        run: |
          git clone https://github.com/AyaELMAFHOUM/pipeline-exercice-ddd.git
          ls -al Exercice-DDD
          ls -R Exercice-DDD
      - name: Build with Maven
        run: |
          cd Exercice-DDD/scouting-service
          mvn clean verify
      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd Exercice-DDD/scouting-service
          mvn sonar:sonar \
            -Dsonar.projectKey=scouting-service \
            -Dsonar.host.url=https://c1b0-197-230-25-154.ngrok-free.app  \
            -Dsonar.login=$SONAR_TOKEN